alias fll='fileutil ls -l -a -h -F -sharded -summary'
alias fls='fileutil ls -h -F -sharded -summary'
alias fmv='fileutil mv -sharded'
alias frm='fileutil rm -sharded'
alias fdel='fileutil recursivedeletegfsbackup'
alias fdu='fileutil du -h -sharded'
alias fcat='fileutil cat -a'
alias ftee='fileutil tee'
alias fcp='fileutil cp -R -a -f'
alias fmkdir='fileutil mkdir -p'
alias frmdir='fileutil rmdir'

alias g='gqui from'
alias count='gqui "select count(*)" from'
alias -g cout='proto research_cluston.ClustonOutput'
alias -g ypd='proto quality_local_ranking.LocalYpData'
alias -g gfv='proto research_scam.GenericFeatureVector'
alias -g ypr='proto quality_local_ranking.LocalYpDataRecord'

alias print_artemis_doc='/google/bin/releases/localweb-indexing/public/print_artemis_doc'
alias jarvis_cli='/google/data/ro/teams/ke-graph-exp/tools/jarvis_cli'
alias demo_hosted='/google/bin/releases/search-quality-eval-hosted/demo_hosted'
alias eval_hosted='/google/bin/releases/search-quality-eval-hosted/eval_hosted'
alias bgrep='/google/data/ro/teams/borgtools/bgrep'
alias bkill='/google/data/ro/teams/borgtools/bkill'
alias build_cleaner='build_cleaner'
alias spiffy='/google/data/ro/projects/superroot/spiffy'
alias servo='/google/data/ro/teams/ml-serving/mpm/servomatic_cli/servomatic_default/servo'
