# vi: ft=swayconfig
output HEADLESS-1 resolution 1920x1200@60Hz

output * allow_tearing yes
output * max_render_time off

input * events disabled
input "48879:57005:Keyboard_passthrough" {
    events enabled
    xkb_layout "us"
    xkb_options "caps:super"
}
input "48879:57005:Mouse_passthrough" events enabled
input "48879:57005:Mouse_passthrough_(absolute)" events enabled
input "48879:57005:Touch_passthrough" events enabled
input "48879:57005:Pen_passthrough" events enabled
input "1356:3302:Sunshine_PS5_(virtual)_pad_Touchpad" events enabled

# Flat acceleration for mouse passthrough
input "48879:57005:Mouse_passthrough" accel_profile flat
input "48879:57005:Mouse_passthrough_(absolute)" accel_profile flat

include $HOME/.config/sway/config
