#!/bin/sh

TZ="America/New_York"
WIDTH=${WIDTH:-20}
HEIGHT=${HEIGHT:-20}
DATEFMT=${DATEFMT:-"+%A, %B %d,"}

OPTIND=1
while getopts ":f:W:H:" opt; do
    case $opt in
        f) DATEFMT="$OPTARG" ;;
        W) WIDTH="$OPTARG" ;;
        H) HEIGHT="$OPTARG" ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            exit 1
            ;;
    esac
done

case "$BLOCK_BUTTON" in
  1|2|3) 

	# the position of the upper left corner of the popup
	posX=$(($BLOCK_X - $WIDTH / 2))
	posY=$(($BLOCK_Y+5))

	i3-msg -q "exec yad --calendar \
             --width=$WIDTH --height=$HEIGHT \
             --undecorated --fixed \
             --close-on-unfocus --no-buttons \
             --posx=$posX --posy=$posY \
             > /dev/null"
esac
echo "$LABEL$(date "$DATEFMT")"
