#!/usr/bin/env bash

url="https://api.exchangeratesapi.io/latest?base=TRY&symbols=USD,EUR" 
raw_data="$(curl -s "$url" |\
            jq -r '.rates |
                   map_values(1/.) |
                   to_entries |
                   map("[\(.key)]=\(.value)") |
                   .[]' |\
            xargs)"

declare -A data="(${raw_data[@]})"

if [[ $BLOCK_BUTTON -gt 1 ]]; then
  printf "USD %.3f, EUR %.3f" ${data[USD]} ${data[EUR]}
else
  printf "%.3f" ${data[USD]}
fi
