#!/bin/bash

layout=$(setxkbmap -query|grep layout|tr -s ' '|cut -d' ' -f 2)

if [[ $BLOCK_BUTTON -eq 1 ]]; then
  if [[ $layout == "us" ]]; then
    setxkbmap tr -option "ctrl:nocaps"
    layout="tr"
  else
    setxkbmap us -option "ctrl:nocaps"
    layout="us"
  fi
fi

echo $layout
