#!/bin/bash

STEP=53
curbl=$(brightnessctl -q -d intel_backlight get)

case $BLOCK_BUTTON in
  4) brightnessctl -q -d intel_backlight set $((curbl+STEP)) ;;
  5) brightnessctl -q -d intel_backlight set $((curbl-STEP)) ;;
esac

curbl=$(brightnessctl -q -d intel_backlight get)
max=$(brightnessctl -q -d intel_backlight max)

echo "☀ $((100*curbl/max))%"

