#!/usr/bin/env bash

# Menu with keys/commands
typeset -A menu
menu=(
  [Shutdown]="systemctl poweroff"
  [Reboot]="systemctl reboot"
  [Hibernate]="systemctl hibernate"
  [Lock]="i3lock --color=000000"
  [Logout]="i3-msg exit"
)
menu_nrows=${#menu[@]}

# Menu entries that may trigger a confirmation message
menu_confirm="Shutdown Reboot Hibernate Logout"

launcher_options=(-fullscreen true
                  -font "Fira Mono 30"
                  -dmenu
                  -i
                  )


launcher=(rofi -lines "${menu_nrows}" -p "Options" "${launcher_options[@]}")
selection="$(printf '%s\n' "${!menu[@]}" | sort | "${launcher[@]}")"

function ask_confirmation() {
  confirmed=$(echo -e "Yes\nNo" |\
    rofi  "${launcher_options[@]}" -lines 2 -p "${selection}?")
  [ "${confirmed}" == "Yes" ] && confirmed=0

  if [ "${confirmed}" == 0 ]; then
    i3-msg -q "exec ${menu[${selection}]}"
  fi
}

if [[ $? -eq 0 && ! -z ${selection} ]]; then
  if [[ ${menu_confirm} =~ (^|[[:space:]])"${selection}"($|[[:space:]]) ]]; then
    ask_confirmation
  else
    i3-msg -q "exec ${menu[${selection}]}"
  fi
fi
