#!/usr/bin/env bash

# Menu entries that may trigger a confirmation message
menu_nrows=6
confirm="Shutdown Reboot Hibernate Logout"
opts=(-yoffset -300 -width 100 -padding $(($(xwininfo -root |awk '/Height/ { print $2}')/2)) -dmenu -i -font "Fira Mono 30")

typeset -A menu
menu=(
[0 Sleep]="systemctl suspend"
[1 Hibernate]="systemctl hibernate"
[2 Shutdown]="systemctl poweroff"
[3 Reboot]="systemctl reboot"
[4 Logout]="i3-msg exit"
[5 Lock]="i3lock --color=000000"
)

if [[ -z $sel ]]; then
  sel="$(printf '%s\n' "${!menu[@]}" | sort | \
    rofi -lines "${menu_nrows}" -p "Options" "${opts[@]}")"
fi

[[ -z $sel ]] && exit 0

if [[ ${confirm} == *${sel}* ]]; then
  confirmed=$(echo -e "Yes\nNo" |\
    rofi  "${opts[@]}" -lines 2 -p "${sel}?")
  if [[ "${confirmed}" == "Yes" ]]; then
    ${menu[${sel}]}
  fi
else
  ${menu[${sel}]}
fi
