#!/bin/bash

# eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
# export SSH_AUTH_SOCK

export TZ="America/New_York"


(
gdbus monitor -y -d org.freedesktop.login1 | \
  command grep -oP "(?<='LockedHint': <)[^>]*" --line-buffered | \
    while read line
    do
      pactl set-sink-mute @DEFAULT_SINK@ $line
    done
  ) &
