hi  Normal        ctermbg=16    ctermfg=231   cterm=NONE  guibg=#000000  guifg=#ffffff  gui=NONE
hi  Boolean       ctermbg=bg    ctermfg=67    cterm=NONE  guibg=bg       guifg=#5f87af  gui=NONE
hi  ColorColumn   ctermbg=bg    ctermfg=235   cterm=NONE  guibg=bg       guifg=#262626  gui=NONE
hi  Comment       ctermbg=bg    ctermfg=95    cterm=NONE  guibg=bg       guifg=#875f5f  gui=NONE
hi  Constant      ctermbg=bg    ctermfg=231   cterm=NONE  guibg=bg       guifg=#ffffff  gui=NONE
hi  Cursor        ctermbg=166   ctermfg=16    cterm=NONE  guibg=#d75f00  guifg=#000000  gui=NONE
hi  CursorColumn  ctermbg=235   ctermfg=NONE  cterm=NONE  guibg=#262626  guifg=NONE     gui=NONE
hi  CursorLine    ctermbg=235   ctermfg=NONE  cterm=NONE  guibg=#262626  guifg=NONE     gui=NONE
hi  CursorLineNr  ctermbg=bg    ctermfg=223   cterm=NONE  guibg=bg       guifg=#ffd7af  gui=NONE
hi  Delimiter     ctermbg=bg    ctermfg=173   cterm=NONE  guibg=bg       guifg=#d7875f  gui=NONE
hi  DiffAdd       ctermbg=235   ctermfg=230   cterm=NONE  guibg=#262626  guifg=#ffffd7  gui=NONE
hi  DiffChange    ctermbg=235   ctermfg=248   cterm=NONE  guibg=#262626  guifg=#a8a8a8  gui=NONE
hi  DiffDelete    ctermbg=bg    ctermfg=88    cterm=NONE  guibg=bg       guifg=#870000  gui=NONE
hi  DiffText      ctermbg=235   ctermfg=173   cterm=NONE  guibg=#262626  guifg=#d7875f  gui=NONE
hi  Directory     ctermbg=bg    ctermfg=231   cterm=NONE  guibg=bg       guifg=#ffffff  gui=NONE
hi  Error         ctermbg=88    ctermfg=230   cterm=NONE  guibg=#870000  guifg=#ffffd7  gui=NONE
hi  ErrorMsg      ctermbg=88    ctermfg=231   cterm=NONE  guibg=#870000  guifg=#ffffff  gui=NONE
hi  FoldColumn    ctermbg=bg    ctermfg=235   cterm=NONE  guibg=bg       guifg=#262626  gui=NONE
hi  Folded        ctermbg=bg    ctermfg=95    cterm=NONE  guibg=bg       guifg=#875f5f  gui=NONE
hi  Function      ctermbg=bg    ctermfg=222   cterm=NONE  guibg=bg       guifg=#ffd787  gui=NONE
hi  Identifier    ctermbg=bg    ctermfg=248   cterm=NONE  guibg=bg       guifg=#a8a8a8  gui=NONE
hi  Ignore        ctermbg=bg    ctermfg=95    cterm=NONE  guibg=bg       guifg=#875f5f  gui=NONE
hi  IncSearch     ctermbg=166   ctermfg=16    cterm=NONE  guibg=#d75f00  guifg=#000000  gui=NONE
hi  LineNr        ctermbg=bg    ctermfg=137   cterm=NONE  guibg=bg       guifg=#af875f  gui=NONE
hi  MatchParen    ctermbg=95    ctermfg=221   cterm=bold  guibg=#875f5f  guifg=#ffd75f  gui=bold
hi  ModeMsg       ctermbg=bg    ctermfg=221   cterm=NONE  guibg=bg       guifg=#ffd75f  gui=NONE
hi  MoreMsg       ctermbg=bg    ctermfg=221   cterm=NONE  guibg=bg       guifg=#ffd75f  gui=NONE
hi  NonText       ctermbg=bg    ctermfg=88    cterm=NONE  guibg=bg       guifg=#870000  gui=NONE
hi  Number        ctermbg=bg    ctermfg=67    cterm=NONE  guibg=bg       guifg=#5f87af  gui=NONE
hi  Operator      ctermbg=bg    ctermfg=173   cterm=NONE  guibg=bg       guifg=#d7875f  gui=NONE
hi  Pmenu         ctermbg=235   ctermfg=248   cterm=NONE  guibg=#262626  guifg=#a8a8a8  gui=NONE
hi  PmenuSbar     ctermbg=bg    ctermfg=231   cterm=NONE  guibg=bg       guifg=#ffffff  gui=NONE
hi  PmenuSel      ctermbg=235   ctermfg=221   cterm=NONE  guibg=#262626  guifg=#ffd75f  gui=NONE
hi  PmenuThumb    ctermbg=bg    ctermfg=231   cterm=NONE  guibg=bg       guifg=#ffffff  gui=NONE
hi  PreProc       ctermbg=bg    ctermfg=215   cterm=NONE  guibg=bg       guifg=#ffaf5f  gui=NONE
hi  Question      ctermbg=bg    ctermfg=230   cterm=NONE  guibg=bg       guifg=#ffffd7  gui=NONE
hi  Search        ctermbg=180   ctermfg=16    cterm=NONE  guibg=#d7af87  guifg=#000000  gui=NONE
hi  Special       ctermbg=bg    ctermfg=215   cterm=NONE  guibg=bg       guifg=#ffaf5f  gui=NONE
hi  SpecialKey    ctermbg=bg    ctermfg=67    cterm=NONE  guibg=bg       guifg=#5f87af  gui=NONE
hi  SpellBad      ctermbg=NONE  ctermfg=88    cterm=NONE  guibg=NONE     guifg=#870000  gui=NONE  guisp=#870000
hi  SpellCap      ctermbg=NONE  ctermfg=221   cterm=NONE  guibg=NONE     guifg=#ffd75f  gui=NONE  guisp=#ffd75f
hi  SpellLocal    ctermbg=NONE  ctermfg=88    cterm=NONE  guibg=NONE     guifg=#870000  gui=NONE  guisp=#870000
hi  SpellRare     ctermbg=NONE  ctermfg=180   cterm=NONE  guibg=NONE     guifg=#d7af87  gui=NONE  guisp=#d7af87
hi  Statement     ctermbg=bg    ctermfg=166   cterm=NONE  guibg=bg       guifg=#d75f00  gui=NONE
hi  StatusLineNC  ctermbg=bg    ctermfg=235   cterm=NONE  guibg=bg       guifg=#262626  gui=NONE
hi  String        ctermbg=bg    ctermfg=180   cterm=NONE  guibg=bg       guifg=#d7af87  gui=NONE
hi  TabLine       ctermbg=bg    ctermfg=95    cterm=NONE  guibg=bg       guifg=#875f5f  gui=NONE
hi  TabLineFill   ctermbg=235   ctermfg=231   cterm=NONE  guibg=#262626  guifg=#ffffff  gui=NONE
hi  TabLineSel    ctermbg=bg    ctermfg=221   cterm=NONE  guibg=bg       guifg=#ffd75f  gui=NONE
hi  Title         ctermbg=bg    ctermfg=230   cterm=bold  guibg=bg       guifg=#ffffd7  gui=bold
hi  Todo          ctermbg=bg    ctermfg=231   cterm=bold  guibg=bg       guifg=#ffffff  gui=bold
hi  Type          ctermbg=bg    ctermfg=223   cterm=NONE  guibg=bg       guifg=#ffd7af  gui=NONE
hi  Underlined    ctermbg=235   ctermfg=221   cterm=NONE  guibg=#262626  guifg=#ffd75f  gui=NONE
hi  VertSplit     ctermbg=bg    ctermfg=235   cterm=NONE  guibg=bg       guifg=#262626  gui=NONE
hi  Visual        ctermbg=215   ctermfg=16    cterm=NONE  guibg=#ffaf5f  guifg=#000000  gui=NONE
hi  VisualNOS     ctermbg=bg    ctermfg=231   cterm=NONE  guibg=bg       guifg=#ffffff  gui=NONE
hi  WarningMsg    ctermbg=bg    ctermfg=221   cterm=NONE  guibg=bg       guifg=#ffd75f  gui=NONE
hi  WildMenu      ctermbg=bg    ctermfg=221   cterm=NONE  guibg=bg       guifg=#ffd75f  gui=NONE
