#!/usr/bin/env zsh

opts=(-width 100 -dmenu -i -font "Fira Mono 30")

TABS_JSON=$(chrome-remote-interface list |\
            jq -r 'map(select(.type=="page"))
                 | to_entries
                 | map({value: .value.id, key: "#\(.key) \(.value.title)"})
                 | from_entries')

TAB_NAMES=$(echo "$TABS_JSON" | jq -r 'keys[]')
TAB=$(echo "$TAB_NAMES"|rofi ${opts})
[[ -z $TAB ]] && exit 0

cur_ws=$(i3-msg -t get_workspaces|jq 'map(select(.visible))|.[].num')
init_urgents=( $(i3-msg -t get_workspaces|jq 'map(select(.urgent))|.[].name') )

tab=$(echo $TABS_JSON|jq -r ".\"$TAB\"")
if chrome-remote-interface activate $tab &>/dev/null
then

  final_urgents=( $(i3-msg -t get_workspaces|jq 'map(select(.urgent))|.[].name') )
  if [[ $#final_urgents -eq 1  ]];  then
    i3-msg workspace $final_urgents
    exit 0
  fi

  diff=(${final_urgents:|init_urgents})

  if [[ $#diff -eq 1 && ! $cur_ws -eq ${diff[0]} ]];  then
    i3-msg workspace $diff
    exit 0
  fi

  if [[ $#diff -eq 0 ]]; then
    i3-msg scratchpad show
  fi

fi
exit 1

