#!/usr/bin/env bash

PASS_DIR=~/.password-store

# Handle argument.
if [ -n "$@" ]; then
    PASS_FILE="$@"
fi

if [[ -f "${PASS_DIR}/${PASS_FILE}.gpg" ]]; then
  coproc ( /usr/bin/pass -c $(basename ${PASS_FILE})  >/dev/null 2>&1 )
  exec 1>&-
  exit;
fi

# Print formatted listing
ls --color=never $PASS_DIR|sed 's/.gpg$//'
