#!/bin/bash
pkill -0 swayidle
status=$?

if [[ "$BLOCK_BUTTON" -eq 1 ]]; then
  if (( status  )); then
    nohup swayidle &>/dev/null &
    status=0
  else
    pkill swayidle
    status=1
  fi
fi

if (( status )); then
  echo "👁"
else
  echo "💤"
fi
