#!/bin/bash

pkill -f -0 xautolock
status=$?

if [[ $BLOCK_BUTTON -eq 1 ]]
then
  if (( $status ))
  then
    i3-msg exec -- --no-startup-id xautolock -detectsleep -time 1 -locker '/usr/share/goobuntu-desktop-files/xsecurelock.sh' &>/dev/null
    status=0
  else
    xautolock -exit
    status=1
  fi
fi

if (( $status ))
then
  echo 👁
else
  echo 💤
fi
