#!/usr/bin/env bash
typeset -A menu
symbols=(    )
actions=(Sleep Shutdown Reboot Lock Logout)
cmds=("systemctl suspend-then-hibernate"
      "systemctl poweroff"
      "systemctl reboot"
      "/usr/share/goobuntu-desktop-files/xsecurelock.sh"
      "i3-msg exit")



shutdown=""
reboot=""
lock=""
suspend=""
logout=""

if [[ -z $sel ]]; then
  sel="$(printf '%s\n' "${symbols[@]}" | rofi -theme shutdown -dmenu -format i)"
fi

[[ -z $sel ]] && exit

# Menu entries that may trigger a confirmation message
confirmation_required="1 2 4"
# if confirmation is not required; or it is obtained
if [[ ${confirmation_required} != *${sel}* || \
  $(echo -e "✓\n✗" | rofi -format i -dmenu -theme shutdown-confirm -p "${actions[${sel}]}") == 0 ]]
then
  ${cmds[${sel}]}
fi
