#!/bin/bash

read var

if [[ "$var" == http* ]]
then
  xdg-open "$var" &>/dev/null
elif [[ -f "$var" &&  ( "$var" == *.pdf || "$var" == *.jpg || "$var" == *.png ) ]]
then
  xdg-open "$var" &>/dev/null
elif [[ "$var" == go/* || "$var" == b/* || "$var" == cl/* ]]
then
  xdg-open http://"$var" &>/dev/null
elif [[ "$var" == "Change "*  || "$var" == "CL"* ]]; then
  xdg-open http://cl/"${var#* }" &>/dev/null
elif [[ "$var" == "⬞"* ]]
then
  xdg-open http://cl/"${var#⬞}" &>/dev/null
else
  tmux set-buffer $var
  tmux paste-buffer
fi
