# vi: fdm=marker
# Set FZF before running tmux-selector as the latter uses the former.
[ -f /usr/share/doc/fzf/examples/key-bindings.zsh ] && source /usr/share/doc/fzf/examples/key-bindings.zsh
export FZF_DEFAULT_COMMAND="fd --type f"
export FZF_DEFAULT_OPTS="--border --layout=reverse"
export FZF_CTRL_T_OPTS="--preview='less {}'"

() {
  local -A WORKSTATION_REMOTES=(
    laptop "ofis cloud ev"
    ofis   "cloud"
  )
  local -a extra_args=()
  if [[ -z $SSH_TTY && -n "${WORKSTATION_REMOTES[$WORKSTATION_NAME]}" ]]; then
    local -a remotes=( ${(s: :)WORKSTATION_REMOTES[$WORKSTATION_NAME]} )
    extra_args=( ${(f)"$(printf '--extra\nSSH: %s| exec ssh %s\n' "${remotes[@]:^remotes}")"} )
  fi
  source "$ZDOTDIR/tmux-selector/tmux-selector.zsh" "${extra_args[@]}"
}

if [[ "$WORKSTATION_NAME" == "cloud" ]]; then
  gcertstatus --nocheck_ssh --quiet || gcert --disable_svelte
  if [[ -z $SNAP_BASHRC_SOURCED && -r /google/data/ro/teams/ix-ml/snap/config/bashrc ]]; then
    source /google/data/ro/teams/ix-ml/snap/config/bashrc
  fi
  export SNAP_DEFAULT_FOR_SYNC=true
  export SNAP_DEFAULT_FOR_NEW_WORKSPACE=true
fi

# set shell options {{{
eval "$(dircolors $ZDOTDIR/dircolors)"

setopt ALWAYS_TO_END
setopt AUTO_CD
setopt AUTO_CONTINUE
setopt AUTO_NAME_DIRS
setopt AUTO_PUSHD
setopt BRACE_CCL
setopt CDABLE_VARS
setopt COMBINING_CHARS
setopt NO_COMPLETE_ALIASES
setopt COMPLETE_IN_WORD
setopt CORRECT
setopt EXTENDED_GLOB
setopt EXTENDED_HISTORY
setopt GLOB_ASSIGN
setopt GLOB_STAR_SHORT
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_FCNTL_LOCK
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_LEX_WORDS
setopt HIST_REDUCE_BLANKS
setopt HIST_SUBST_PATTERN
setopt HIST_VERIFY
setopt INTERACTIVE_COMMENTS
setopt LIST_ROWS_FIRST
setopt LONG_LIST_JOBS
setopt MAGIC_EQUAL_SUBST
setopt MAIL_WARNING
setopt MARK_DIRS
setopt NO_CASE_GLOB
setopt NO_FLOW_CONTROL
setopt NO_HUP
setopt NO_NOMATCH
setopt NUMERIC_GLOB_SORT
setopt PROMPT_BANG
setopt PROMPT_SUBST
setopt PUSHD_IGNORE_DUPS
setopt PUSHD_SILENT
setopt PUSHD_TO_HOME
setopt RC_EXPAND_PARAM
setopt RC_QUOTES
setopt REMATCH_PCRE
setopt SHARE_HISTORY
setopt TRANSIENT_RPROMPT

# }}}

# Completion Styles from zprezto {{{
# Use caching to make completion for commands such as dpkg and apt usable.
zstyle ':completion::complete:*' use-cache on
zstyle ':completion::complete:*' cache-path "$HOME/.dotfiles/tmp/.zcompcache"

# Case-insensitive (all), partial-word, and then substring completion.
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

# Group matches and describe.
zstyle ':completion:*:*:*:*:*' menu select
zstyle ':completion:*:matches' group 'yes'
zstyle ':completion:*:options' description 'yes'
zstyle ':completion:*:options' auto-description '%d'
zstyle ':completion:*:corrections' format ' %F{green}-- %d (errors: %e) --%f'
zstyle ':completion:*:descriptions' format ' %F{yellow}-- %d --%f'
zstyle ':completion:*:messages' format ' %F{purple} -- %d --%f'
zstyle ':completion:*:warnings' format ' %F{red}-- no matches found --%f'
zstyle ':completion:*:default' list-prompt '%S%M matches%s'
zstyle ':completion:*' format ' %F{yellow}-- %d --%f'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' verbose yes

# Fuzzy match mistyped completions.
zstyle ':completion:*' completer _complete _match _approximate
zstyle ':completion:*:match:*' original only
zstyle ':completion:*:approximate:*' max-errors 1 numeric

# Increase the number of errors based on the length of the typed word. But make
# sure to cap (at 7) the max-errors to avoid hanging.
zstyle -e ':completion:*:approximate:*' max-errors 'reply=($((($#PREFIX+$#SUFFIX)/3>7?7:($#PREFIX+$#SUFFIX)/3))numeric)'

# Don't complete unavailable commands.
zstyle ':completion:*:functions' ignored-patterns '(_*|pre(cmd|exec))'

# Array completion element sorting.
zstyle ':completion:*:*:-subscript-:*' tag-order indexes parameters

# Directories
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*:*:cd:*' tag-order local-directories directory-stack path-directories
zstyle ':completion:*:*:cd:*:directory-stack' menu yes select
zstyle ':completion:*:-tilde-:*' group-order 'path-directories' 'named-directories' 'users' 'expand'
zstyle ':completion:*' squeeze-slashes true
zstyle ':completion:*' add-space true

# History
zstyle ':completion:*:history-words' stop yes
zstyle ':completion:*:history-words' remove-all-dups yes
zstyle ':completion:*:history-words' list false
zstyle ':completion:*:history-words' menu yes

# Environmental Variables
zstyle ':completion::*:(-command-|export):*' fake-parameters ${${${_comps[(I)-value-*]#*,}%%,*}:#-*-}

# Populate hostname completion. But allow ignoring custom entries from static
# */etc/hosts* which might be uninteresting.
#zstyle -a ':prezto:module:completion:*:hosts' etc-host-ignores '_etc_host_ignores'

zstyle -e ':completion:*:hosts' hosts 'reply=(
  ${=${=${=${${(f)"$(cat {/etc/ssh_,~/.ssh/known_}hosts(|2)(N) 2> /dev/null)"}%%[#| ]*}//\]:[0-9]*/ }//,/ }//\[/ }
  ${=${${${${(@M)${(f)"$(cat ~/.ssh/config 2> /dev/null)"}:#Host *}#Host }:#*\**}:#*\?*}}
)'
# ${=${(f)"$(cat /etc/hosts(|)(N) <<(ypcat hosts 2> /dev/null))"}%%(\#${_etc_host_ignores:+|${(j:|:)~_etc_host_ignores}})*}

# Don't complete uninteresting users...
zstyle ':completion:*:*:*:users' users $USER root

# ... unless we really want to.
zstyle '*' single-ignored show

# Ignore multiple entries.
zstyle ':completion:*:(rm|kill|diff):*' ignore-line other
zstyle ':completion:*:rm:*' file-patterns '*:all-files'

# Kill
zstyle ':completion:*:*:*:*:processes' command 'ps -u $LOGNAME -o pid,user,command -w'
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#) ([0-9a-z-]#)*=01;36=0=01'
zstyle ':completion:*:*:kill:*' menu yes select
zstyle ':completion:*:*:kill:*' force-list always
zstyle ':completion:*:*:kill:*' insert-ids single

# Man
zstyle ':completion:*:manuals' separate-sections true
zstyle ':completion:*:manuals.(^1*)' insert-sections true

# SSH/SCP/RSYNC
zstyle ':completion:*:(ssh|scp|rsync):*' tag-order 'hosts:-host:host hosts:-domain:domain hosts:-ipaddr:ip\ address *'
zstyle ':completion:*:(scp|rsync):*' group-order users files all-files hosts-domain hosts-host hosts-ipaddr
zstyle ':completion:*:ssh:*' group-order users hosts-domain hosts-host users hosts-ipaddr
zstyle ':completion:*:(ssh|scp|rsync):*:hosts-host' ignored-patterns '*(.|:)*' loopback ip6-loopback localhost ip6-localhost broadcasthost
zstyle ':completion:*:(ssh|scp|rsync):*:hosts-domain' ignored-patterns '<->.<->.<->.<->' '^[-[:alnum:]]##(.[-[:alnum:]]##)##' '*@*'
zstyle ':completion:*:(ssh|scp|rsync):*:hosts-ipaddr' ignored-patterns '^(<->.<->.<->.<->|(|::)([[:xdigit:].]##:(#c,2))##(|%*))' '127.0.0.<->' '255.255.255.255' '::1' 'fe80::*'

# }}}

# ZLE settings {{{
bindkey -v

# show ... while completing {{{
function expand-or-complete-with-indicator {
  zle split-undo
  local indicator="..."
  print -Pn "$indicator"
  zle expand-or-complete
  zle redisplay
}
zle -N expand-or-complete-with-indicator
bindkey -M viins "\C-I" expand-or-complete-with-indicator
bindkey -M viins "\C-x " expand-word
# }}}

# prepend sudo {{{
function prepend-sudo {
  if [[ "$BUFFER" != su(do|)\ * ]]; then
    if [[ "$BUFFER" == "v "* ]]; then
      BUFFER="sudoedit ${BUFFER#v }"
      (( CURSOR += 8 ))
    else
      BUFFER="sudo $BUFFER"
      (( CURSOR += 5 ))
    fi
  fi
}
zle -N prepend-sudo
bindkey -M viins "\C-s" prepend-sudo
#}}}

# dotdotdot {{{
function expand-dot-to-parent-directory-path {
  if [[ $ZLE_STATE == *insert* ]]; then
   if [[ $LBUFFER == "g4 "*" .."  || $LBUFFER == "blaze "*" .." ]]; then
      LBUFFER+='.'
    elif [[ $LBUFFER == *.. ]]; then
      LBUFFER+='/..'
    else
      LBUFFER+='.'
    fi
  else
    LBUFFER+='.'
    RBUFFER=${RBUFFER:1}
  fi
}
zle -N expand-dot-to-parent-directory-path
bindkey -M viins  "." expand-dot-to-parent-directory-path
bindkey -M isearch . self-insert 2>/dev/null # necessary? don't expand during incsearch
# }}}

# make multiline {{{
function break-spaces-to-new-lines {
  RBUFFER="${(pj: \\\n:)${(s: :)RBUFFER}}"
}
zle -N break-spaces-to-new-lines
bindkey -M vicmd "\C-w" break-spaces-to-new-lines
bindkey -M viins "\C-w" break-spaces-to-new-lines

function break-flags-to-new-lines {
  RBUFFER="${(pj: \\\n  -:)${(s: -:)RBUFFER}}"
}
zle -N break-flags-to-new-lines
bindkey -M vicmd "\C-e" break-flags-to-new-lines
bindkey -M viins "\C-e" break-flags-to-new-lines
# }}}

# custom line join that deletes \ at the end of lines{{{
function vi-join-custom {
  local lines=(${(f)RBUFFER})
  lines[1]=${lines[1]/% #\\}
  RBUFFER=${(F)lines}
  zle vi-join
}

zle -N vi-join-custom
bindkey -M vicmd J vi-join-custom
# }}}

# sharded {{{
function glob-to-sharded {
  BUFFER="${BUFFER//-?????-of-0#/@}"
}
zle -N glob-to-sharded
bindkey -M vicmd "\C-a" glob-to-sharded
bindkey -M viins "\C-a" glob-to-sharded
# }}}

# copy the earlier word {{{
autoload -Uz copy-earlier-word
zle -N copy-earlier-word
bindkey -M viins "\em" copy-earlier-word
#}}}

# edit command in vi {{{
autoload -Uz edit-command-line
zle -N edit-command-line
bindkey -M vicmd "\ee" edit-command-line
bindkey -M viins "\ee" edit-command-line
# }}}

# magic space with undo {{{
function magic-space-with-undo {
  zle split-undo
  zle magic-space
}
zle -N magic-space-with-undo
bindkey -M viins " " magic-space-with-undo
# }}}

autoload -Uz url-quote-magic
zle -N self-insert url-quote-magic

# cancel the esc in command mode
# and fix zle reset-prompt multiline-deletion bug for a few things
# it is not a complete fix tho, surround commands still delete the
# line above.
zsh-widget-noop () {}
zle -N zsh-widget-noop
bindkey -M vicmd '\e' zsh-widget-noop
bindkey -M viins '\eA' zsh-widget-noop
bindkey -M viins '\ea' zsh-widget-noop
bindkey -M viins '\eI' zsh-widget-noop
bindkey -M viins '\ei' zsh-widget-noop
bindkey -M viins '\eO' zsh-widget-noop
bindkey -M viins '\eo' zsh-widget-noop

zmodload zsh/terminfo

for mode in viins vicmd; do
  bindkey -M $mode "$terminfo[khome]" beginning-of-line
  bindkey -M $mode "$terminfo[kend]"  end-of-line
  bindkey -M $mode "\e[H"             beginning-of-line
  bindkey -M $mode "\e[F"             end-of-line
  bindkey -M $mode "$terminfo[kcuu1]" history-beginning-search-backward
  bindkey -M $mode "$terminfo[kcud1]" history-beginning-search-forward
  bindkey -M $mode "\e[A"             history-beginning-search-backward
  bindkey -M $mode "\e[B"             history-beginning-search-forward
  bindkey -M $mode "$terminfo[kcbt]"  reverse-menu-complete
  bindkey -M $mode "$terminfo[kdch1]" delete-char
  bindkey -M $mode "$terminfo[kbs]"   backward-delete-char
  bindkey -M $mode "\C-?"             backward-delete-char
  bindkey -M $mode "\C-q"             push-input
  bindkey -M $mode "\eq"              get-line
  bindkey -M $mode "\ek" history-beginning-search-backward
  bindkey -M $mode "\ej" history-beginning-search-forward
done

bindkey -M viins "\e[1;5D" backward-word       #  ctrl left
bindkey -M viins "\e[1;5C" forward-word        #  ctrl right
bindkey -M viins "\e[3;6~" kill-word           #  ctrl shift del
bindkey -M viins "\e[3;5~" backward-kill-word  #  ctrl del
bindkey -M viins "\e[3;3~" backward-kill-line  #  alt  del
bindkey -M viins "\C-z"    undo

# add surround-operation to zle {{{
autoload -Uz surround
zle -N surround
zle -N delete-surround surround
zle -N add-surround surround
zle -N change-surround surround
bindkey -a cs change-surround
bindkey -a ds delete-surround
bindkey -a ys add-surround
bindkey -M visual S add-surround
# }}}

# bracket/quote text objects {{{
autoload -U select-bracketed select-quoted
zle -N select-bracketed
zle -N select-quoted
  for km in viopp visual; do
  bindkey -M $km -- '-' vi-up-line-or-history
  for c in {a,i}"${(s..):-\'\"\`\|,./:;-=+@}"; do
    bindkey -M $km $c select-quoted
  done
  for c in {a,i}${(s..):-'()[]{}<>bB'}; do
    bindkey -M $km $c select-bracketed
  done
done
#}}}

# clipboard integration {{{
if [[ -n $TMUX ]]
then
  function cutbuffer() {
    zle .$WIDGET
    printf "\033]52;c;$(printf "%s" "$CUTBUFFER" | base64 | tr -d '\n')\a"
  }

  function putbuffer() {
    zle copy-region-as-kill "$(tmux save-buffer -)"
    zle .$WIDGET
  }
elif [[ -n $WAYLAND_DISPLAY ]] && (( $+commands[wl-copy] ))
then
  function cutbuffer() {
    zle .$WIDGET
    printf "%s" "$CUTBUFFER" | wl-copy
  }

  function putbuffer() {
    zle copy-region-as-kill "$(wl-paste -n)"
    zle .$WIDGET
  }
fi

(( $+functions[cutbuffer] )) && {
  zle_cut_widgets=( vi-backward-delete-char vi-change vi-change-eol
  vi-change-whole-line vi-delete vi-delete-char vi-kill-eol vi-substitute
  vi-yank vi-yank-eol kill-word backward-kill-word vi-backward-kill-word
  vi-kill-line )

  for widget in $zle_cut_widgets; do
    zle -N $widget cutbuffer
  done


  zle_put_widgets=( vi-put-after vi-put-before )
  for widget in $zle_put_widgets; do
    zle -N $widget putbuffer
  done
}
# }}}

typeset -x GREEN=$'%F{#72B233}' ORANGE=$'%F{#FF6400}' PURPLE=$'%F{#6400FF}' PINK=$'%F{#FF0064}'
function _mode_indicator {
  if [[ $KEYMAP == "main" || $KEYMAP == "viins" ]]; then
    if [[ $ZLE_STATE == *insert* ]]; then
      PROMPT_COLOR=$ORANGE
    else
      PROMPT_COLOR=$PINK
    fi
  else
    PROMPT_COLOR=$PURPLE
  fi
  zle reset-prompt
}

function zle-line-init {
  if [[ -n $ZLE_LINE_ABORTED ]]; then
    local savebuf="$BUFFER" savecur="$CURSOR"
    BUFFER="$ZLE_LINE_ABORTED"
    CURSOR="$#BUFFER"
    zle split-undo
    BUFFER="$savebuf" CURSOR="$savecur"
  fi
  _mode_indicator
}
zle -N zle-line-init

function zle-keymap-select {
  _mode_indicator $@
}
zle -N zle-keymap-select

# custom line join {{{
function vi-join-custom {
  zle vi-join
  BUFFER=${BUFFER//\\ / }
}

zle -N vi-join-custom
bindkey -M vicmd J vi-join-custom
# }}}

# }}}

# theme {{{
function set-theme {
  # bold (pink # if sudo) green name (@ host if SSH) | green
  local cl='%F{black} %f'
  PS1="%B$PINK%(!.%# .)$GREEN%n${SSH_CONNECTION+@$WORKSTATION_NAME}%f | $GREEN"
  PS1+='%(1v.$CITC_NAME %f%b(%(2v.'$cl'%2v. 📤) @'$cl'%1v ) %B| .)'
  PS1+='$GREEN%(1v.${CITC_PWD+//$CITC_PWD}.%d)'
  PS1+=$'\n%{\r%}$PROMPT_COLOR❯%b%f '

  b=" %f|$PINK "
  RPS1='%B$PINK${CONDA_PREFIX+$CONDA_PREFIX:t%(0?.%(1j.$b.).$b)}'
  RPS1+='%(0?..%?%(1j.$b.))%(1j.%j bg jobs.)%f%b'
}
set-theme
tabs -2
# }}}

HISTFILE="$HOME/.dotfiles/tmp/history"
HISTSIZE=12000
SAVEHIST=10000

for p in $HOME/.dotfiles/bin $HOME/.local/bin 
do
  if ! (( $path[(I)$p] ))
  then
    path=($p $path)
  fi
done

fpath=($ZDOTDIR/autoload $ZDOTDIR/zsh-completions/src $fpath)

if [[ -f /google/src/files/head/depot/google3/devtools/blaze/scripts/zsh_completion ]]
then
  fpath=(
    $(realpath /google/src/files/head/depot/google3/devtools/blaze/scripts/zsh_completion)
    $fpath
  )
fi

# Remove platform-specific completions for other OSes
fpath=(${fpath:#*/Completion/(AIX|BSD|Cygwin|Darwin|Solaris|openSUSE|Redhat|Mandriva)})

for i ($ZDOTDIR/autoload/^_*(:t)) autoload -U $i

source "$ZDOTDIR/aliases"
source "$ZDOTDIR/g4d/setup.zsh"

SAVEDDIRS="$HOME/.dotfiles/tmp/dirs"
source "$ZDOTDIR/savedir/setup.zsh"

KEYTIMEOUT=10
PROMPT_EOL_MARK=' [no EOL]'

# load some 'features' {{{
autoload -U zmv
zmodload zsh/pcre
#source /etc/zsh_command_not_found
disable r # do not use shell built-in r for repeating last command
autoload -Uz compinit
# Always call compinit, but use cache if less than 24h old
if [[ -n ~/.dotfiles/tmp/zcompdump(N.mh-24) ]]; then
  compinit -C -i -d ~/.dotfiles/tmp/zcompdump
else
  compinit -i -d ~/.dotfiles/tmp/zcompdump
  touch ~/.dotfiles/tmp/zcompdump
fi
unset "_comps[open]"
# compile zcompdump
{
  zcomp="$HOME/.dotfiles/tmp/zcompdump" 
  if [[ -s "$zcomp" && (! -s "${zcomp}.zwc" || "${zcomp}" -nt "${zcomp}.zwc") ]]
  then 
    zcompile "$zcomp"
  fi
} &!
#}}}

# syntax highlighting {{{
function _load_fast_highlight() {
  source $ZDOTDIR/syntax-highlight/fast-syntax-highlighting.plugin.zsh
  FAST_HIGHLIGHT[chroma-ssh]=""
  FAST_HIGHLIGHT[chroma-make]=""
  FAST_HIGHLIGHT_STYLES[globbing]='fg=magenta,underlined'
  FAST_HIGHLIGHT_STYLES[history-expansion]='fg=magenta,bold'
  FAST_HIGHLIGHT_STYLES[function]='fg=green,bold'
  FAST_HIGHLIGHT_STYLES[alias]='fg=green,bold'
  FAST_HIGHLIGHT_STYLES[comment]='fg=101'
}
sched +1 _load_fast_highlight
# }}}

# Auto-compile large zsh scripts in the background
function _auto_zcompile() {
  local files=(
    "$ZDOTDIR/zshrc"
    "$ZDOTDIR/syntax-highlight/fast-syntax-highlighting.plugin.zsh"
    "$ZDOTDIR/syntax-highlight/fast-highlight"
    "$ZDOTDIR/g4d/async.zsh"
    "$ZDOTDIR/autoload/_blaze"
    "$ZDOTDIR/autoload/_g4_generated_completion"
  )
  local f
  for f in $files; do
    if [[ -s "$f" && (! -s "${f}.zwc" || "$f" -nt "${f}.zwc") ]]; then
      zcompile "$f"
    fi
  done
}
{ _auto_zcompile } &!
